# Generated by Django 3.2.7 on 2021-09-25 03:34

from django.db import migrations, models
import review.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('body', models.TextField()),
                ('score', models.FloatField(default=3, null=True, validators=[review.validators.validate_score])),
            ],
        ),
    ]
