# Generated by Django 3.2.7 on 2021-09-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_type', models.CharField(choices=[('simple_widget_d', '대상포진'), ('simple_widget_a', 'A형 간염'), ('simple_widget_g', '가다실')], default='all_vaccine', help_text='백신 종류', max_length=31)),
                ('description', models.CharField(blank=True, help_text='병원설명', max_length=255, null=True)),
                ('name', models.CharField(blank=True, help_text='병원이름', max_length=63, null=True)),
            ],
        ),
    ]
