# Generated by Django 3.2.7 on 2021-09-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210925_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='detail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='maxprice',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='minprice',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='writer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
